spring:
  datasource:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password: 1111

    spring:
      datasource:
        url: jdbc:mysql://localhost:3306/order_mgmt  # 데이터베이스 URL
        username: root                     # 데이터베이스 사용자명
        password: 1111                            # 데이터베이스 비밀번호
        driver-class-name: org.mariadb.jdbc.Driver           # MariaDB 드라이버 클래스